version: "3"

services:
  informix:
    image: ibmcom/informix-developer-database:latest
    environment:
      LICENSE: accept
      INIT_FILE: init-database.sql
    ports:
      - "9088-9089:9088-9089"
      - "2022:2022"
      - "27018:27018"
      - "27017:27017"
      - "27883:27883"
    tty: true
    volumes:
      - "./informix-init/init-database.sql:/opt/ibm/config/init-database.sql"
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      SERVICES: dynamodb,s3
  init-dynamodb:
    build: ..
    image: topcoder-skills-etl:latest
    command:
      - "/app/scripts/init-dynamodb.js"
    environment:
      S3_ENDPOINT: http://localstack:4566
      DYNAMODB_ENDPOINT: http://localstack:4566
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - "../scripts/dynamodb-data.json:/app/scripts/dynamodb-data.json"
    depends_on:
      - localstack
    restart: on-failure
  init-s3:
    build: ..
    image: topcoder-skills-etl:latest
    command:
      - "/app/scripts/init-s3.js"
    environment:
      S3_ENDPOINT: http://localstack:4566
      DYNAMODB_ENDPOINT: http://localstack:4566
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - "../scripts/tagsMap.txt:/app/scripts/tagsMap.txt"
    depends_on:
      - localstack
    restart: on-failure

networks:
  default:
    name: skills-etl