FROM node:14

RUN apt-get update -y && apt-get install -y default-jdk

WORKDIR /app

ARG INFORMIX_HOST
ARG INFORMIX_PORT
ARG INFORMIX_USER
ARG INFORMIX_PASSWORD
ARG INFORMIX_DATABASE
ARG INFORMIX_SERVER
ARG MINPOOL
ARG MAXPOOL
ARG MAXSIZE
ARG IDLETIMEOUT
ARG TIMEOUT
ARG DYNAMODB_ENDPOINT
ARG AWS_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG TAGS_MAP_FILE
ARG MAX_DAYS_FOR_CHALLENGE_SKILLS

ENV INFORMIX_HOST=$INFORMIX_HOST
ENV INFORMIX_PORT=$INFORMIX_PORT
ENV INFORMIX_USER=$INFORMIX_USER
ENV INFORMIX_PASSWORD=$INFORMIX_PASSWORD
ENV INFORMIX_DATABASE=$INFORMIX_DATABASE
ENV INFORMIX_SERVER=$INFORMIX_SERVER
ENV MINPOOL=$MINPOOL
ENV MAXPOOL=$MAXPOOL
ENV MAXSIZE=$MAXSIZE
ENV IDLETIMEOUT=$IDLETIMEOUT
ENV TIMEOUT=$TIMEOUT
ENV DYNAMODB_ENDPOINT=$DYNAMODB_ENDPOINT
ENV AWS_REGION=$AWS_REGION
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV TAGS_MAP_FILE=$TAGS_MAP_FILE
ENV MAX_DAYS_FOR_CHALLENGE_SKILLS=$MAX_DAYS_FOR_CHALLENGE_SKILLS

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY ./config ./config
COPY ./scripts ./scripts
COPY ./src ./src
COPY ./index.js ./index.js

ENTRYPOINT ["node"]
